version: "3.8"
services:
    postgres:
        image: postgres:17
        container_name: forum_postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        command: >
            postgres 
            -c password_encryption=scram-sha-256
            -c log_connections=on
            -c log_statement=all

volumes:
    postgres_data:
